Repository Konkuk-ThanksD/Server, pull requests merged in 2023-10, with the labels that each got.

#3 feat: 테스팅 용 이메일 회원가입 및 로그인 기능 구현
  build.gradle
  src/main/java/com/thanksd/server/config/SecurityConfig.java
  src/main/java/com/thanksd/server/config/SwaggerConfig.java
  src/main/java/com/thanksd/server/controller/AuthController.java
  src/main/java/com/thanksd/server/controller/MemberController.java
  src/main/java/com/thanksd/server/domain/BaseTime.java
  src/main/java/com/thanksd/server/domain/Member.java
  src/main/java/com/thanksd/server/domain/Platform.java
  src/main/java/com/thanksd/server/dto/request/AuthLoginRequest.java
  src/main/java/com/thanksd/server/dto/request/MemberSignUpRequest.java
  src/main/java/com/thanksd/server/dto/response/MemberSignUpResponse.java
  src/main/java/com/thanksd/server/dto/response/Response.java
  src/main/java/com/thanksd/server/dto/response/TokenResponse.java
  src/main/java/com/thanksd/server/exception/badrequest/BlankTokenException.java
  src/main/java/com/thanksd/server/exception/badrequest/DuplicateMemberException.java
  src/main/java/com/thanksd/server/exception/badrequest/InvalidEmailException.java
  src/main/java/com/thanksd/server/exception/badrequest/InvalidPasswordException.java
  src/main/java/com/thanksd/server/exception/badrequest/InvalidPlatformException.java
  src/main/java/com/thanksd/server/exception/badrequest/PasswordMismatchException.java
  src/main/java/com/thanksd/server/exception/notfound/NotFoundMemberException.java
  src/main/java/com/thanksd/server/exception/unauthorized/InvalidBearerException.java
  src/main/java/com/thanksd/server/exception/unauthorized/InvalidTokenException.java
  src/main/java/com/thanksd/server/exception/unauthorized/TokenExpiredException.java
  src/main/java/com/thanksd/server/repository/MemberRepository.java
  src/main/java/com/thanksd/server/security/auth/AuthenticationPrincipalArgumentResolver.java
  src/main/java/com/thanksd/server/security/auth/AuthorizationExtractor.java
  src/main/java/com/thanksd/server/security/auth/JwtTokenProvider.java
  src/main/java/com/thanksd/server/security/auth/LoginInterceptor.java
  src/main/java/com/thanksd/server/security/auth/LoginUserId.java
  src/main/java/com/thanksd/server/service/AuthService.java
  src/main/java/com/thanksd/server/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/thanksd/server/AuthServiceTest.java
  src/test/java/com/thanksd/server/MemberServiceTest.java
  src/test/java/com/thanksd/server/ServiceTest.java
  src/test/java/com/thanksd/server/support/DatabaseCleaner.java
  src/test/java/com/thanksd/server/support/DatabaseCleanerCallback.java
  src/test/resources/application.yml
Labels: 문서화, 기능 구현

#4 fix: 누락된 인터셉터 및 BaseTimeConfig 파일 추가
  src/main/java/com/thanksd/server/config/AuthConfig.java
  src/main/java/com/thanksd/server/config/BaseTimeConfig.java
  src/main/java/com/thanksd/server/controller/ControllerAdvice.java
  src/test/java/com/thanksd/server/domain/BaseTimeTest.java
  src/test/java/com/thanksd/server/repository/RepositoryTest.java
  src/test/java/com/thanksd/server/service/AuthServiceTest.java
  src/test/java/com/thanksd/server/service/MemberServiceTest.java
  src/test/java/com/thanksd/server/service/ServiceTest.java
Labels: 🚨버그🚨, 기능 구현

#6 feat: github actions CI 스크립트 작성
  .github/workflows/ci-backend.yml
Labels: 인프라

#8 feat: Google OAuth 2.0 로그인 구현
  build.gradle
  src/main/java/com/thanksd/server/controller/AuthController.java
  src/main/java/com/thanksd/server/dto/request/GoogleLoginRequest.java
  src/main/java/com/thanksd/server/exception/unauthorized/InvalidGoogleTokenException.java
  src/main/java/com/thanksd/server/security/auth/google/AuthProperties.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleAuthClient.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleInfoClient.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleInfoResponse.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleOAuthUserProvider.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleTokenRequest.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleTokenResponse.java
  src/main/java/com/thanksd/server/service/AuthService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 기능 구현

#7 feat: 일기 기본 CRUD 작성
  src/main/java/com/thanksd/server/config/AuthConfig.java
  src/main/java/com/thanksd/server/controller/DiaryController.java
  src/main/java/com/thanksd/server/domain/Diary.java
  src/main/java/com/thanksd/server/domain/Member.java
  src/main/java/com/thanksd/server/dto/request/DiaryRequest.java
  src/main/java/com/thanksd/server/dto/response/DiaryAllResponse.java
  src/main/java/com/thanksd/server/dto/response/DiaryIdResponse.java
  src/main/java/com/thanksd/server/dto/response/DiaryResponse.java
  src/main/java/com/thanksd/server/exception/badrequest/MemberMismatchException.java
  src/main/java/com/thanksd/server/exception/notfound/NotFoundDiaryException.java
  src/main/java/com/thanksd/server/repository/DiaryRepository.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/main/java/com/thanksd/server/service/MemberService.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: 기능 구현

#9 feat: Member 엔티티에 Nation 컬럼 추가
  src/main/java/com/thanksd/server/domain/Member.java
  src/main/java/com/thanksd/server/domain/Nation.java
  src/main/java/com/thanksd/server/dto/request/OAuthMemberSignUpRequest.java
  src/main/java/com/thanksd/server/exception/badrequest/InvalidNationException.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleAuthProperties.java
  src/main/java/com/thanksd/server/security/auth/google/GoogleOAuthUserProvider.java
  src/main/java/com/thanksd/server/service/AuthService.java
  src/main/java/com/thanksd/server/service/MemberService.java
  src/test/java/com/thanksd/server/domain/BaseTimeTest.java
  src/test/java/com/thanksd/server/service/AuthServiceTest.java
  src/test/java/com/thanksd/server/service/MemberServiceTest.java
Labels: 기능 구현

#10 feat: 해당 달에 일기가 존재하는 날짜 조회 기능 구현
  src/main/java/com/thanksd/server/controller/DiaryController.java
  src/main/java/com/thanksd/server/domain/BaseTime.java
  src/main/java/com/thanksd/server/domain/Diary.java
  src/main/java/com/thanksd/server/dto/response/DiaryDateResponse.java
  src/main/java/com/thanksd/server/repository/DiaryRepository.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: 기능 구현
