Repository Konkuk-ThanksD/Server, pull requests merged in 2023-11, with the labels that each got.

#11 feat: s3연결 및 이미지 업로드 기능 추가
  build.gradle
  src/main/java/com/thanksd/server/ServerApplication.java
  src/main/java/com/thanksd/server/config/S3Config.java
  src/main/java/com/thanksd/server/controller/DiaryController.java
  src/main/java/com/thanksd/server/domain/Diary.java
  src/main/java/com/thanksd/server/dto/request/DiaryUpdateRequest.java
  src/main/java/com/thanksd/server/dto/response/PreSignedUrlResponse.java
  src/main/java/com/thanksd/server/exception/badrequest/InvalidImageNameException.java
  src/main/java/com/thanksd/server/exception/badrequest/InvalidImageUrlException.java
  src/main/java/com/thanksd/server/repository/MemberRepository.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/main/java/com/thanksd/server/service/PreSignedUrlService.java
  src/main/resources/application.yml
  src/test/java/com/thanksd/server/ServerApplicationTests.java
  src/test/java/com/thanksd/server/security/auth/JwtTokenProviderTest.java
  src/test/java/com/thanksd/server/service/AuthServiceTest.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
  src/test/java/com/thanksd/server/service/MemberServiceTest.java
  src/test/java/com/thanksd/server/service/ServiceTest.java
  src/test/resources/application.yml
Labels: 기능 구현

#12 feat: 해당 날짜에 존재하는 일기 조회 기능 구현
  src/main/java/com/thanksd/server/controller/ControllerAdvice.java
  src/main/java/com/thanksd/server/controller/DiaryController.java
  src/main/java/com/thanksd/server/dto/response/DiaryInfoListResponse.java
  src/main/java/com/thanksd/server/dto/response/DiaryInfoResponse.java
  src/main/java/com/thanksd/server/repository/DiaryRepository.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/main/resources/application.yml
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: 기능 구현

#15 feat: 유효하지 않은 년도 혹은 달에 대해 예외 처리 추가
  src/main/java/com/thanksd/server/exception/badrequest/InvalidDateException.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: 🚨버그🚨

#14 feat: 일기 삭제 시, s3에 업로드 되어 있는 이미지도 같이 삭제 기능 추가
  src/main/java/com/thanksd/server/controller/DiaryController.java
  src/main/java/com/thanksd/server/domain/Diary.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/main/java/com/thanksd/server/service/PreSignedUrlService.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: 기능 구현

#20 fix: BaseTime 오류 해결 및 날짜별 일기 조회 로직 수정
  src/main/java/com/thanksd/server/domain/BaseTime.java
  src/main/java/com/thanksd/server/repository/DiaryRepository.java
  src/main/java/com/thanksd/server/service/DiaryService.java
Labels: 🚨버그🚨

#22 feat: 회원 탈퇴 기능 추가
  src/main/java/com/thanksd/server/controller/MemberController.java
  src/main/java/com/thanksd/server/service/MemberService.java
  src/test/java/com/thanksd/server/service/MemberServiceTest.java
Labels: 기능 구현

#23 feat: 오늘 날짜가 포함된 주에 작성한 일기 개수를 반환하는 기능 추가
  src/main/java/com/thanksd/server/controller/DiaryController.java
  src/main/java/com/thanksd/server/dto/response/DiaryWeekCountResponse.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: 기능 구현

#25 fix: 일기가 존재하는 날짜 반환 기능에서 리스트 중복 제거 로직 추가
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/main/resources/application.yml
Labels: 🚨버그🚨

#24 fix: Diary content,font 삭제
  src/main/java/com/thanksd/server/domain/Diary.java
  src/main/java/com/thanksd/server/dto/request/DiaryRequest.java
  src/main/java/com/thanksd/server/dto/request/DiaryUpdateRequest.java
  src/main/java/com/thanksd/server/dto/response/DiaryResponse.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: 🚨버그🚨, ✏️ API 변경

#26 feat: 일기 조회 로직 이미지 자체를 전달하도록 변경
  src/main/java/com/thanksd/server/controller/DiaryController.java
  src/main/java/com/thanksd/server/dto/response/DiaryAllResponse.java
  src/main/java/com/thanksd/server/service/DiaryService.java
  src/main/java/com/thanksd/server/service/PreSignedUrlService.java
  src/test/java/com/thanksd/server/service/DiaryServiceTest.java
Labels: ✏️ API 변경

#27 fix: presignedUrl 요청 메서드 POST -> GET으로 수정
  src/main/java/com/thanksd/server/controller/DiaryController.java
Labels: 🚨버그🚨
